apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: rbc-test-app-2
spec:
  application: rbc-test-app-2
  container:
    containers:
    - image: ghcr.io/digital-garage-icl/student-rbc-test-app-2:latest
      name: ui
      ports:
      - containerPort: 8080
        name: ui
        protocol: TCP
      securityContext:
        runAsGroup: 999
        runAsUser: 999
    expose:
      container: ui
      port: 8080
    tls: true
  name: rbc-test-app-2
  type: Container