apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: app-name-placeholder
spec:
  application: app-name-placeholder
  container:
    containers:
    - image: ghcr.io/digital-garage-icl/repo-name-placeholder:latest
      name: ui
      ports:
      - containerPort: 8080
        name: ui
        protocol: TCP
      securityContext:
        runAsGroup: 999
        runAsUser: 999
    expose:
      container: ui
      port: 8080
    tls: true
  name: app-name-placeholder
  type: Container